### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Yashi30**

### CODE REVIEW

**Comment by Yashi30** [comment]
This repo is not contributing towards hactoberfest-accepted  , i think you have to add label at the time of merging.

**Comment by Neeraj319** [comment]
I read the docs of hacktoverfest it says the repo with the hacktoverfest label will be accepted if the merge is successful or the repo owner should label it for getting the pr to be accepted here is the full statement from hacktoberfest :
pull requests will only count toward earning a T-shirt or planting a tree if they are labeled as ‘hacktoberfest-accepted’ by a maintainer, or submitted in a repository classified with the ‘hacktoberfest’ topic. Pull requests in repositories with the ‘hacktoberfest’ topic will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.

**Comment by Yashi30** [comment]
Yeah !! I also read that but  my contributions in your repo  is not contributing towards hacktoberfest .. I also don't know why

**Comment by Yashi30** [comment]
I got the point , You have to add the label named Hacktoberfest-accepted not hactobetfest-accepted, please do this correction.

**Comment by Yashi30** [comment]
Thanks for your efforts but please correct the label instead of writing
hactoberfest-accepted you have written hactobetfest-accepted, please
correct this issue
Once again thanks

**Comment by Neeraj319** [comment]
i think it is fine now hope it worked

**Comment by Yashi30** [comment]
Yeah it worked now thank you so much

**Comment by Neeraj319** [comment]
thanks for your contribution and happy to help

**Pull request merged**
